name: Build Project

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [master]

jobs:
  build_android:
    name: "Build Android"
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: "Run generate script"
        run: ./bldsys/scripts/generate_android_gradle.bat
#      - name: "Explicitly setup SDK path with local.properties."
#        run: |
#          echo "sdk.dir=/usr/local/android-sdk" > build/android_gradle/local.properties
#          echo "ndk.dir=/usr/local/android-ndk" >> build/android_gradle/local.properties
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: "Build Android using gradlew."
        working-directory: build/android_gradle
        run: ./gradlew app:assembleRelease
